/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-container": "#dad7ff",
        "tertiary": "#7e3000",
        "primary-container": "#4f46e5",
        "surface-tint": "#4d44e3",
        "on-surface": "#191c1e",
        "on-primary": "#ffffff",
        "surface": "#f7f9fb",
        "surface-variant": "#e0e3e5",
        "primary-fixed": "#e2dfff",
        "on-tertiary": "#ffffff",
        "error-container": "#ffdad6",
        "on-secondary-fixed": "#001e2f",
        "on-primary-fixed-variant": "#3323cc",
        "tertiary-fixed-dim": "#ffb695",
        "inverse-surface": "#2d3133",
        "on-tertiary-fixed-variant": "#7b2f00",
        "secondary-fixed": "#c9e6ff",
        "outline-variant": "#c7c4d8",
        "on-secondary": "#ffffff",
        "surface-container-highest": "#e0e3e5",
        "on-error": "#ffffff",
        "surface-container": "#eceef0",
        "surface-bright": "#f7f9fb",
        "on-secondary-container": "#004666",
        "surface-container-high": "#e6e8ea",
        "surface-dim": "#d8dadc",
        "background": "#f7f9fb",
        "on-secondary-fixed-variant": "#004c6e",
        "secondary-fixed-dim": "#89ceff",
        "on-tertiary-fixed": "#351000",
        "inverse-on-surface": "#eff1f3",
        "on-tertiary-container": "#ffd2be",
        "tertiary-fixed": "#ffdbcc",
        "surface-container-low": "#f2f4f6",
        "on-primary-fixed": "#0f0069",
        "outline": "#777587",
        "on-error-container": "#93000a",
        "primary": "#3525cd",
        "on-background": "#191c1e",
        "on-surface-variant": "#464555",
        "secondary-container": "#39b8fd",
        "tertiary-container": "#a44100",
        "surface-container-lowest": "#ffffff",
        "inverse-primary": "#c3c0ff",
        "error": "#ba1a1a",
        "primary-fixed-dim": "#c3c0ff",
        "secondary": "#006591",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "container-padding": "1.5rem",
        "gutter": "1rem",
        "sidebar-width": "280px",
        "chat-max-width": "800px",
        "stack-gap-sm": "0.5rem",
        "stack-gap-md": "1rem",
      },
      fontFamily: {
        body: ["Inter", "system-ui", "sans-serif"],
      },
      fontSize: {
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-sm": ["11px", { lineHeight: "14px", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
}
